# Generated by Django 2.1.1 on 2018-10-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('eng_name', models.CharField(max_length=255)),
                ('headImg', models.FileField(upload_to='./upload/')),
            ],
        ),
    ]
